steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/singlepage:$SHORT_SHA', '-f', 'Dockerfile', '.']
    id: build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/singlepage:$SHORT_SHA']
    id: push
    waitFor:
      - build
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/singlepage', 'singlepage=gcr.io/$PROJECT_ID/singlepage:$SHORT_SHA', '--record']
    id: release
    waitFor:
      - push
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
