steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/singlepage:pr-$_PR_NUMBER', '-f', 'Dockerfile', '.']
    id: build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/singlepage:pr-$_PR_NUMBER']
    id: push
    waitFor:
      - build
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '--image=gcr.io/$PROJECT_ID/singlepage:pr-$_PR_NUMBER'
      - '--app=singlepage-review-pr-$_PR_NUMBER'
      - '--cluster=cluster-1'
      - '--location=us-central1-c'
    id: release
    waitFor:
      - push
