steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/wawd-269408/singlepage:latest', '-f', 'Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/singlepage', 'singlepage=gcr.io/wawd-269408/singlepage:latest', '--record']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east4-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
